### ISSUE TITLE
CSV not uploading via 

### ISSUE THREAD

**Issue by mannylopez** [mapbox/mapbox-file-sniff#32]
```Error: Unknown filetype``` is shown when trying to upload a CSV file to https://www.mapbox.com/uploads/

CSV file used: https://mapbox.slack.com/files/geografa/F09HSPN0J/points.csv

The same file uploads without a hitch when dragging into the online editor or opening via https://www.mapbox.com/editor/#data

cc @rclark @GretaCB @mapbox/support

**Comment by mannylopez** [comment]
The console spits this error message out:
```Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)```

**Comment by mannylopez** [comment]
Reference HS ticket
https://secure.helpscout.net/conversation/114685593/28953/

**Comment by rclark** [comment]
This error occurs in mapbox-file-sniff v0.3.1 and below, but was fixed in v0.4.0. The error you're seeing is coming off of a library that is using an out-of-date version of mapbox-file-sniff.

**Comment by jontroncoso** [comment]
This is still an issue. I'm using the web app directly, not a native app. 
doesn't work: https://www.mapbox.com/studio/data/ 
works: https://www.mapbox.com/editor/#data

I realize this may not be an issue with mapbox-file-sniff directly. Is there a github repo for the web app (https://www.mapbox.com/studio/data/) where I can open an issue so they can implement the latest version of mapbox-file-sniff?

**Comment by tmcw** [comment]
@jontroncoso does your CSV file have longitude & latitude information in it? /editor/ will automatically geocode data, /studio/data/ will not, hence the difference.

**Comment by jontroncoso** [comment]
No, it has addresses in it. I was hoping mapbox would geocode it for me. I suppose that makes sense. I will read the docs to see if I can create a dataset with `/studio/data` . If not, I'll have to code my own solution locally. Thanks for the quick reply!

**Comment by jontroncoso** [comment]
For those who find this in the future, I was able to successfully do this: 
- go to https://www.mapbox.com/editor/#data
- click the [import] link (where it says "Draw or [import]  .geojson, .csv, .kml, or .gpx files.")
- upload your CSV
- click [project]
- click GeoJSON (this will give you a JSON file)
- use that JSON file to upload to https://www.mapbox.com/studio/data/ 


I was worried that my superfluous data would be trimmed by `/editor` but it was not :) pretty awesome tool guys!

**Comment by fedex1** [comment]
A possibly related issue is: it seems that the 
`
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

occurs if you have a large GeoJSON file that is all on one line.  For example, see https://cityregister.firebaseapp.com/nycdobjobsrecent.geojson

I upload that file and I see the 422 error

But if I format it with json_pp 

For example,

`json_pp < nycdobjobsrecent.geojson > nycdobjobsrecent_formatted.geojson
`

and load nycdobjobsrecent_formatted.geojson it works.

**Comment by fedex1** [comment]
My recent comment relates to https://www.mapbox.com/studio/data/ upload issues

**Comment by rclark** [comment]
@fedex1 see #35
